### ISSUE TITLE
AttributeError in print_results

### ISSUE THREAD

**Issue by zifban** [alhoo/jf#4]
```
Traceback (most recent call last):
  File "bin/jf", line 11, in <module>
    sys.exit(main())
  File "jf/__main__.py", line 122, in main
    print_results(data, args)
  File "lib/python3.5/site-packages/jf/output.py", line 45, in print_results
    out = json.loads(json.dumps(out.data, cls=StructEncoder),
AttributeError: 'str' object has no attribute 'data'
```

**Comment by alhoo** [comment]
Thanks for reporting!
